### ISSUE TITLE
关于log 的显示

### ISSUE THREAD

**Issue by Jeff2Ma** [Youmoo/qos-node-client#4]
希望可以弄个loglevel 的option 控制log 的输出，一般而言我是希望开发时候显示必要的log，而到了生产环境则是禁止掉。

**Comment by Youmoo** [comment]
好的，这几天我抽空加一下。

@Jeff2Ma 你想在日志中查看哪些信息？

**Comment by Jeff2Ma** [comment]
哈，因为在 [fetch.js 文件](https://github.com/Youmoo/qos-node-client/blob/master/dist/util/fetch.js#L64-L66)里面有个 console.log 导致在用的时候在终端会显示一大串信息，如果不好安排loglevel ，希望可以先删除掉。谢谢回复！

**Comment by Youmoo** [comment]
@Jeff2Ma 最新版本中日志已经去掉。如需启用日志，设置环境变量: DEBUG=qos-node-client:* 即可。

谢谢反馈.
